region: ap-northeast-1
cluster: example-dev-foobar
service: example-dev-foobar
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: "10m0s"
plugins:
  - name: tfstate
    config:
      url: s3://terraform-state-naritomo/example/dev/cicd/app_foobar_v1.0.0.tfstate